### PR TITLE
Add GameOverScene to handle when the space shooter ends

### PR DESCRIPTION
**Pull request by squid-ai**
GameOverScene will display the game over and any additional buttons/actions the player can choose from. 
Adding buttons in progress

### CODE REVIEW

**Comment by Zeelot** [comment]
I can't seem to quit the game any more. Do you know why?

image

**Comment by squid-ai** [comment]
I think we ran into this issue before but need to recall/debug this some more though to fix it

**Comment by squid-ai** [comment]
Debugging was easier than I expected :) game should quit now

**Review by Zeelot — APPROVED** [review]
woo!

**Pull request merged**
