### PR TITLE
docs tooling

### PR DESCRIPTION
**Pull request by Zeelot**
I want to use https://www.mkdocs.org for generating our docs site so we can write tutorials and other content in markdown files in the `docs/` folder.

https://pdoc.dev generates documentation from parsing our python code and seems like a lighter weight tool than Sphinx. It only generates html files for now but they have a ticket for supporting markdown file output (https://github.com/mitmproxy/pdoc/issues/308). I want to generate markdown files from our python so that they can be embedded with the markdown in `docs/` and be turned into one `mkdocs` site with proper search across both tutorials and API docs. This PR uses the `pdoc` tool's ability to specify a custom template to create a hacky `markdown` template along with a little script that helps us rename `.html` files to `.md`.

I committed all the generated `html` so that we can configure `GitHub Pages` to host the site for us once this merges to master. These are the commands you need to run in order to regenerate the docs and I'll use other tickets to create the CI pipelines to run them automatically for us in the future:

```bash
bin/build-docs
mkdocs build
```

### CODE REVIEW

**Comment by Zeelot** [comment]
hey @mhils, I think I'm getting close, but I am noticing that the docblock gets parsed and generated the `Args` and `Returns` headers as `h6` but I am trying to make them generate as `h3` elements. Do you know if this can be tweaked somehow? It seems to be part of the parsing logic more than the rendering template.

**Comment by mhils** [comment]
The conversion to Markdown is done at https://github.com/mitmproxy/pdoc/blob/caf801833e85349d5bdd276f4877552a3fc00291/pdoc/docstrings.py#L154, I'm afraid that's not really tweakable per output type. I'd say that converting all ######s to ###s would be fine with me, it shouldn't be much of a loss in practice.

**Comment by Zeelot** [comment]
Thanks for the quick feedback! I went ahead and made all the changes you pointed out and cleaned other things up quite a bit (I think). Here's the latest screenshot:

image

@mhils: I have one last bit that is nagging me and I don't think it's related to markdown specifically. For undocumented methods, I would still like to render the `Args` and `Returns` sections with as much detail as possible. If the method arguments are type-hinted, I should be able to render all the relevant information minus any descriptions. Un-type-hinted methods should still be able to show argument names and order. This is my example method:
image

Any idea how complex this would be to open as a feature request? I don't think I will block this PR on the work unless I am just missing something that already exists :) Either way I think we're about done with this PR so thanks again for all the help!

**Comment by Zeelot** [comment]
Oh! Would also love to know how I can test a sub module doc. What would be some example python I could use? I think this is just my inexperience with python and not knowing what would cause pdoc to detect something as a submodule:

image

**Comment by Zeelot** [comment]
@ToddiusNoobius / @squid-ai  I think this is ready to review and merge for now! still not amazing but I think I fixed up all the big issues and at least all of the needed information seems to be available even if it's not displayed in the most pleasant way.

**Comment by mhils** [comment]
> Thanks for the quick feedback! I went ahead and made all the changes you pointed out and cleaned other things up quite a bit (I think). Here's the latest screenshot:
> 
> [...]
> 

This looks excellent! My only stylistic comment would be that I relatively strongly prefer rendering the constructor as `Foo()` as opposed to `__init__`. I feel that's easier to pick up for Python newcomers as it reflects how they would use the API as opposed to how it is implemented. This also matches what Python is doing for its own documentation.
The HTML template should have an example for how to do this.

> @mhils: I have one last bit that is nagging me and I don't think it's related to markdown specifically. For undocumented methods, I would still like to render the `Args` and `Returns` sections with as much detail as possible. If the method arguments are type-hinted, I should be able to render all the relevant information minus any descriptions. Un-type-hinted methods should still be able to show argument names and order. This is my example method: image
> 
> Any idea how complex this would be to open as a feature request? I don't think I will block this PR on the work unless I am just missing something that already exists :) Either way I think we're about done with this PR so thanks again for all the help!

You can access [`func.signature`](https://pdoc.dev/docs/pdoc/doc.html#Function.signature) to get an https://docs.python.org/3/library/inspect.html#inspect.Signature object. That being said, I'd personally lean on not adding such boilerplate. There really is nothing new to be learned from such repetition. If you dislike the empty docstring you should add a short but useful one. :)


> Oh! Would also love to know how I can test a sub module doc. What would be some example python I could use? I think this is just my inexperience with python and not knowing what would cause pdoc to detect something as a submodule:
> 
> image


That's very much an edge case where folks import another package and then add it to `__all__`. The only case where this is really useful is if you everything organized in a bunch of submodules and you want to parent module page just to list a short summary of the submodules. Again, very much an edge case. :)

 Contrived example:

```python
import typing
__all__ = ["typing"]
```

**Comment by Zeelot** [comment]
hey @mhils can you share a link to some python docs that describe class constructors? I was trying to improve the TOC navigation that mkdocs generates on the right and found `__init__()` easier to parse specifically because there is an additional header right above it with the class name itself, so would love to see some examples in order to make a better adjustment. I agree that exposing the `__init__()` name is a bit less than ideal and I did keep the code blocks in the content area the way you had them. I can give this another pass tonight!

Thanks for confirming my guess about the submodule thing. I think I pushed some changes this weekend that should make those areas render properly now.

> You can access func.signature to get an https://docs.python.org/3/library/inspect.html#inspect.Signature object. That being said, I'd personally lean on not adding such boilerplate. There really is nothing new to be learned from such repetition. If you dislike the empty docstring you should add a short but useful one. :)

I think I see what you mean since we are rendering the entire method signature in a code block. I'll leave this out for now!

**Comment by Zeelot** [comment]
Here is a concrete example of the constructor weirdness I was wrestling:
image

**Comment by mhils** [comment]
Here's an example of how pdoc handles this in the HTML template: https://pdoc.dev/docs/pdoc/doc.html#Module
Here's an example how Python documents classes itself: https://docs.python.org/3/library/smtplib.html#smtplib.SMTP

Does that help?

**Comment by Zeelot** [comment]
Yep perfect. I'll iterate a bit more on this tonight :) I think I have some ideas and I just need to poke around with some more mkdocs / markdown extensions!

**Review by ToddiusNoobius — APPROVED** [review]

**Pull request merged**
